spring:
  datasource:
    username: root
    password: Raj#9011
    url: jdbc:mysql://localhost:3306/springboot_restapi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true